name: "Slack Notification - Pull request is opened"

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [main]

jobs: 
  send_slack:
    runs-on: ubuntu-latest
    
    steps:
      - name: Send to Slack
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "PR Details"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "Repository: ${{ toJSON(github.event.repository.full_name) }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "PR Author: ${{ toJSON(github.event.pull_request.user.login) }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "PR Title: ${{ github.event.pull_request.title }}"
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "PR Link: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
