name: "Slack Notification - Pull request is opened"

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [main]

jobs: 
  send_slack:
    runs-on: ubuntu-latest
    
    steps:

      - name: Build Slack payload
        id: payload
        run: |
          AUTHOR="${{ github.event.pull_request.user.login }}"
          
          if [ "$EVENT" = "opened" ]; then
            HEADER="PR opened ðŸš€"
          else
            HEADER="PR Ready for Review ðŸ‘€"
          fi

          
      - name: Slack Notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "PR Details"
            blocks:
             - type: "section"
               text:
                  type: "mrkdwn"
                  text: "********************************\n__HEADER__"
             - type: "section"
               text:
                  type: "mrkdwn"
                  text: "Repository: ${{ github.event.repository.full_name }}\nPR Author: __AUTHOR__ }}\nPR Title: ${{ github.event.pull_request.title }}\nPR Link: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}\nPR Branch: ${{ github.head_ref }}"
