name: "Slack Notification - Pull request is opened"
#dummy change
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [main]

jobs: 
  send_slack:
    runs-on: ubuntu-latest
    
    steps:

      - name: Build Slack payload
        id: payload
        run: |
          EVENT="${{ github.event.action }}"
          REPOSITORY="${{ github.event.repository.full_name }}"
          AUTHOR="${{ github.event.pull_request.user.login }}"
          TITLE="${{ github.event.pull_request.title }}"
          PR_URL="${{ github.event.pull_request.html_url }}"
          PR_COMMIT="${{ github.event.head_commit.url }}"
          BRANCH="${{ github.head_ref }}"
          
          if [ "$EVENT" = "opened" ]; then
            HEADER="PR opened ðŸš€"
          else
            HEADER="PR Ready for Review ðŸ‘€"
          fi

          echo "HEADER=$HEADER" >> $GITHUB_OUTPUT
          echo "REPOSITORY=$REPOSITORY" >> $GITHUB_OUTPUT
          echo "AUTHOR=$AUTHOR" >> $GITHUB_OUTPUT
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT
          echo "PR_URL=$PR_URL" >> $GITHUB_OUTPUT
          echo "PR_COMMIT=$PR_COMMIT" >> $GITHUB_OUTPUT
          echo "BRANCH=$BRANCH" >> $GITHUB_OUTPUT
          
      - name: Slack Notification
        uses: slackapi/slack-github-action@v2.1.1
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "PR Details"
            blocks:
             - type: "section"
               text:
                  type: "mrkdwn"
                  text: "********************************\n${{ steps.payload.outputs.HEADER }}"
             - type: "section"
               text:
                  type: "mrkdwn"
                  text: "Repository: ${{ steps.payload.outputs.REPOSITORY }}\nPR Author: ${{ steps.payload.outputs.AUTHOR }}\nPR Title: ${{ steps.payload.outputs.TITLE }}\nPR Link: ${{ steps.payload.outputs.PR_URL || steps.payload.outputs.PR_COMMIT }}\nPR Branch: ${{ steps.payload.outputs.BRANCH }}"
